/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.flaptor.indextank.rpc;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PageType implements TEnum {
  initial(0),
  optimized(1),
  index(2),
  live(3);

  private final int value;

  private PageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PageType findByValue(int value) { 
    switch (value) {
      case 0:
        return initial;
      case 1:
        return optimized;
      case 2:
        return index;
      case 3:
        return live;
      default:
        return null;
    }
  }
}
